zmblog/web/views.py
"""==========zhuming=========="""

from flask import Blueprint, render_template, redirect, url_for, request

# 创建管理前端的蓝图对象
from back.models import Article

web_blue = Blueprint('web', __name__)


# 首页
@web_blue.route('/', methods=['GET', 'POST'])
def index():
    if request.method == 'GET':
        # 倒序排列文章，最新文章就放5个
        articles = Article.query.order_by(-Article.id).all()
        return render_template('web/index.html', articles=articles)


# 阅读全文/展示全文的页面
@web_blue.route('/info/<int:id>/', methods=['GET', 'POST'])
def info(id):
    if request.method == 'GET':
        article = Article.query.get(id)
        articles = Article.query.order_by(-Article.id).all()
        # 在数据库中id的自动生成有可能被人为的打断顺序，所以不能直接通过对于id的加减进行查询
        # 只能通过取出所有id保存在列表中，根据下标的加减来查询
        ids = [art.id for art in articles]
        # 判断是否只有一篇文章
        pre_article = ''
        if len(ids) > 1:
            pre_id = ids[ids.index(id) - 1]
            pre_article = Article.query.get(pre_id)
        # 判断是否为最后一篇
        next_article = ''
        if id != min(ids):
            next_id = ids[ids.index(id) + 1]
            next_article = Article.query.get(next_id)
        return render_template('web/info.html', article=article,
                               ids=ids, pre_article=pre_article, next_article=next_article)


# 文章列表
@web_blue.route('/list/<int:id>', methods=['GET', 'POST'])
def art_list(id):
    if request.method == 'GET':
        arts = Article.query.order_by(-Article.id).all()
        if id < 1:
            id = 1
        if id*4 > len(arts):
            id = len(arts)//4 + 1
        page = id
        articles = Article.query.order_by(-Article.id).offset((page-1)*4).limit(4).all()
        return render_template('web/list.html', articles=articles, id=id, arts=arts)


# 关于我
@web_blue.route('/about/', methods=['GET', 'POST'])
def about():

    return render_template('web/about.html')


# 留言
@web_blue.route('/gbook/', methods=['GET', 'POST'])
def gbook():

        return render_template('web/gbook.html')

zmblog/templates/web/about.html
{% extends 'web/base_main.html' %}

{% block title %}
    关于博主
{% endblock %}

{% block css %}
    {{ super() }}
    <link href="/static/web/css/about.css" rel="stylesheet">
{% endblock %}

{% block article %}
    <article>
     <h2 class="litle"><span>花儿开在春风里，你笑得甜如蜜。</span>关于我</h2>
     <div class="ab_box">
      <div class="leftbox">
          <div class="newsview">
            <div class="news_infos" style="text-align:center;">
                <p>暂时没什么写的，就放一首诗经吧。</p><br>
             <p>
                蒹葭苍苍，白露为霜。所谓伊人，在水一方，溯洄从之，道阻且长。溯游从之，宛在水中央。<br>
                 蒹葭萋萋，白露未晞。所谓伊人，在水之湄。溯洄从之，道阻且跻。溯游从之，宛在水中坻。<br>
                 蒹葭采采，白露未已。所谓伊人，在水之涘。溯洄从之，道阻且右。溯游从之，宛在水中沚。
             </p>
            </div>
        </div>
        <div class="meandblog">
          <h2>我和我的博客</h2>
          <ul>
            <li><a href="#"
                   target="">博主正在努力中...</a>
            </li>
          </ul>
        </div>
      </div>
      <div class="rightbox">
        <div class="aboutme">
          <h2 class="hometitle">关于我</h2>
          <div class="avatar"> <img src="/static/web/images/tx.JPG"> </div>
          <div class="ab_con">
            <p>网名：woming | 。。。</p>
            <p>职业：游人 </p>
            <p>邮箱：womingly@sina.cn</p>

          </div>
        </div>
        <div class="weixin">
          <h2 class="hometitle">个人微信</h2>
          <ul>
            <img src="/static/web/images/wx.jpg">
          </ul>
        </div>
      </div>
     </div>
    </article>
{% endblock %}

zmblog/templates/web/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>
        {% block title %}
        {% endblock %}
    </title>

    {% block css %}
    {% endblock %}

    {% block js %}
    {% endblock %}

</head>
<body>
    {% block header %}
    {% endblock %}

    {% block article %}
    {% endblock %}

    {% block footer %}
    {% endblock %}

</body>
</html>

zmblog/templates/web/base_main.html
{% extends 'web/base.html' %}

{% block css %}
    <link href="/static/web/css/base.css" rel="stylesheet">
    <link href="/static/web/css/m.css" rel="stylesheet">
    <link rel="icon" type="img/ico" href="/static/web/images/favicon1.ico">
{% endblock %}

{% block js %}
    <!--[if lt IE 9]>
    <script src="/static/web/js/modernizr.js"></script>
    <!--<![endif]&ndash;&gt;-->
    <!--<script>-->
    <!--window.onload = function ()-->
    <!--{-->
        <!--var oH2 = document.getElementsByTagName("h2")[0];-->
        <!--var oUl = document.getElementsByTagName("ul")[0];-->
        <!--oH2.onclick = function ()-->
        <!--{-->
            <!--var style = oUl.style;-->
            <!--style.display = style.display == "block" ? "none" : "block";-->
            <!--oH2.className = style.display == "block" ? "open" : ""-->
        <!--}-->
    <!--}-->
    <!--</script>-->
{% endblock %}


{% block header %}
    <header>
      <!--<div id="mnav">-->
        <!--<h2><span class="navicon"></span></h2>-->
        <!--<ul>-->
          <!--<li><a href="index.html">网站首页</a></li>-->
          <!--<li><a href="about.html">关于我</a></li>-->
          <!--<li><a href="list.html">学无止境</a></li>-->
          <!--<li><a href="gbook.html">留言</a></li>-->
        <!--</ul>-->
      <!--</div>-->
      <nav>
        <ul>
          <li><a href="{{ url_for('web.index') }}">网站首页</a></li>
          <li><a href="{{ url_for('web.about') }}">关于我</a></li>
          <li><a href="{{ url_for('web.art_list', id=1) }}">文章列表</a></li>
          <li><a href="{{ url_for('web.gbook') }}">留言</a></li>
        </ul>
      </nav>
    </header>
{% endblock %}

{% block footer %}
    <footer>
        <p><a href="#">woming个人博客</a> <a href="#">蜀ICP备999999999号-9</a></p>
    </footer>
{% endblock %}

zmblog/templates/web/gbook.html
{% extends 'web/base_main.html' %}

{% block title %}
    留言簿
{% endblock %}

{% block css %}
    {{ super() }}
    <link href="/static/web/css/gbook.css" rel="stylesheet">
{% endblock %}

{% block js %}
    <script src="//cdn1.lncld.net/static/js/3.0.4/av-min.js"></script>
    <script src='//unpkg.com/valine/dist/Valine.min.js'></script>
{% endblock %}


{% block article %}
    <article>
      <h2 class="litle"><span>山有木兮木有枝，心悦君兮君不知。</span>留言</h2>
        <div class="gbko">

        </div>
            <div id="vcomments" class="gbko">
                <script>
                    new Valine({
                        el: '#vcomments',
                        appId: '7ujDnnmxm2RNBSoYMvHApIV4-gzGzoHsz',
                        appKey: 'GsCa5ByL77F1X6o9UB16bKi1',
                        notify:false,
                        verify:false,
                        avatar:'mm',
                        placeholder: '有什么想说的，放心大胆的说吧！反正我也不知道你家地址在哪儿。',
                        pageSize:5,
                    })
                </script>
            </div>


    </article>
{% endblock %}

zmblog/templates/web/index.html
{% extends 'web/base_main.html' %}

{% block title %}
    首页-zhuming个人博客
{% endblock %}

{% block css %}
    {{ super() }}
    <link href="/static/web/css/index.css" rel="stylesheet">
{% endblock %}

{% block js %}
    {{ super() }}
    <script src="/static/web/js/jquery.min.js"></script>
    <script src="/static/web/js/jquery.easyfader.min.js"></script>
{% endblock %}

{% block article %}
    
    <article>
      <div class="banner">
        <div id="sucaihuo" class="fader">
            <img class="slide" src="/static/web/images/banner01.jpg">
            <img class="slide" src="/static/web/images/banner02.jpg">
            <img class="slide" src="/static/web/images/banner03.jpg">
          <div class="fader_controls">
            <div class="page prev" data-target="prev">&lsaquo;</div>
            <div class="page next" data-target="next">&rsaquo;</div>
            <ul class="pager_list">
            </ul>
          </div>
        </div>
        <script>
    $(function() {
        $('#sucaihuo').easyFader();
    });
    </script>
      </div>
    
      <div class="newblogs">
        <h2 class="hometitle">最新文章</h2>
        <ul>
            {% for article in articles %}
            {% if loop.index < 6 %}
              <li>
                  <!--点击标签跳转-->
                <!--<h3 class="blogtitle"><span><a href="#" title="css3" target=""-->
                   <!--class="classname">{{ article.art_tp.tp_name }}</a></span>-->
                    <!--<a href="{{ url_for('web.info', id=article.id) }}"-->
                    <!--target="_blank" >{{ article.title }}</a>-->
                <!--</h3>-->
                  <!--点击标签不跳转-->
                <h3 class="blogtitle"><span><font class="classname">{{ article.art_tp.tp_name }}</font></span>
                    <a href="{{ url_for('web.info', id=article.id) }}"
                    target="_blank" >{{ article.title }}</a>
                </h3>
                <div class="bloginfo"><span class="blogpic">
                    <a href="{{ url_for('web.info', id=article.id) }}" title="" target="_blank">
                    <img src="/static/web/images/b01.jpg"  /></a></span>
                  <p>{{ article.desc }}</p>
                </div>
                <div class="autor"><span class="lm f_l"></span>
                        <span class="dtime f_l">{{ article.create_date }}</span>
                        <!--<span class="viewnum f_l">浏览（<a href="#">999</a>）</span>-->
                        <span class="f_r">
                            <a href="{{ url_for('web.info', id=article.id) }}"
                               target="_blank" class="more">阅读原文>></a>
                        </span>
                </div>
                <div class="line"></div>
              </li>
            {% endif %}
            {% endfor %}

        </ul>
      </div>
        
      <div class="rbox">
        <div class="paihang">
          <h2 class="hometitle">站长推荐</h2>
          <ul>
           {% for article in articles %}
              {% if loop.index < 4 %}
                <!--<li><b><a href="{{ url_for('web.info', id=article.id) }}" target="_blank">{{ article.title }}</a></b>-->
                  <!--<p><i><img src="/static/web/images/b06.jpg"  /></i>{{ article.desc }}..</p>-->
                <!--</li>-->
              {% endif %}
           {% endfor %}
              <!--自定义网络链接-->
                <li><b><a href="https://mp.weixin.qq.com/s/06eYdOJX2dLT6pTWzkYmqA" target="_blank">我再也不登山了</a></b>
                  <p><i><img src="/static/web/images/b06.jpg"  /></i>博主登山经历，有兴趣可以了解一下啊</p>
                </li>
              <li><b><a href="https://mp.weixin.qq.com/s/KgbeMtEdlGzMmCu5T40Nwg" target="_blank">【雀儿】自由之地</a></b>
                  <p><i><img src="/static/web/images/b06.jpg"  /></i>博主第一次登山的队友写的文章</p>
                </li>

          </ul>
        </div>
        <div class="links">
          <h2 class="hometitle">友情链接</h2>
          <ul>
            <li><a href="https://github.com/wwoming">woming-github</a></li>
            <li><a href="https://weibo.com/">weibo</a></li>
            <li><a href="https://www.8264.com/">8264户外资料网</a></li>
          </ul>
        </div>
        <div class="weixin">
          <h2 class="hometitle">个人微信</h2>
          <ul>
              <li>
                  <img src="/static/web/images/wx.jpg" />
              </li>
          </ul>
        </div>
      </div>
    </article>


{% endblock %}

zmblog/templates/web/info.html
{% extends 'web/base_main.html' %}

{% block title %}
    全文-{{ article.title }}
{% endblock %}

{% block css %}
    {{ super() }}
    <link href="/static/web/css/info.css" rel="stylesheet">
{% endblock %}

{% block js %}
    {{ super() }}
<!--评论功能-->
    <script src="//cdn1.lncld.net/static/js/3.0.4/av-min.js"></script>
    <script src='//unpkg.com/valine/dist/Valine.min.js'></script>
{% endblock %}

{% block article %}
    <article>

        <div class="infos">
          <div class="newsview">
            <h2 class="intitle">您现在的位置是：<a href="{{ url_for('web.index') }}">网站首页</a>&nbsp;&gt;
                &nbsp;<a href="">阅读全文</a></h2>
            <h3 class="news_title">{{ article.title }}</h3>
            <div class="news_author"><span class="au01">zhuming</span>
                <span class="au02">{{ article.create_date }}</span>
                <!--<span class="au03">共<b>999</b>人围观</span>-->
            </div>
            <div class="tags">
                <a href="#">{{ article.art_tp.tp_name }}</a>
            </div>
            <div class="news_about"><strong>简介</strong>{{ article.desc }}</div>
            <div class="news_infos">
                {{ article.content | safe }}
            </div>
          </div>
        </div>
        <div class="nextinfo">
            {% if article.id == ids | max %}
            <p>上一篇：<font >无</font></p>
            {% else %}
            <p>上一篇：<a href="{{ url_for('web.info', id=pre_article.id) }}" >{{ pre_article.title }}</a></p>
            {% endif %}

            {% if article.id == ids | min %}
            <p>下一篇：<font >这已经是最后一篇了</font></p>
            {% else %}
            <p>下一篇：<a href="{{ url_for('web.info', id=next_article.id) }}" >{{ next_article.title }}</a></p>
            {% endif %}

        </div>
        <div class="otherlink">
          <h2>相关文章</h2>
          <ul>
            <li><a href="https://mp.weixin.qq.com/s/06eYdOJX2dLT6pTWzkYmqA" target="_blank">我再也不登山了</a></li>
            <li><a href="https://mp.weixin.qq.com/s/KgbeMtEdlGzMmCu5T40Nwg" target="_blank">【雀儿】自由之地</a></li>

          </ul>
        </div>
        <div class="news_pl">
          <h2>文章评论</h2>
            <div id="vcomments" class="gbko">
                <script>
                    new Valine({
                        el: '#vcomments',
                        appId: '7ujDnnmxm2RNBSoYMvHApIV4-gzGzoHsz',
                        appKey: 'GsCa5ByL77F1X6o9UB16bKi1',
                        notify:false,
                        verify:false,
                        avatar:'mm',
                        placeholder: '有什么想说的，放心大胆的说吧！反正我也不知道你家地址在哪儿。',
                        pageSize:5,
                    })
                </script>
            </div>
        </div>

    </article>
{% endblock %}

zmblog/templates/web/list.html
{% extends 'web/base_main.html' %}

{% block title %}
    文章列表
{% endblock %}

{% block css %}
    {{ super() }}
    <link href="/static/web/css/index.css" rel="stylesheet">
{% endblock %}

{% block article %}

    <article>
      <h2 class="litle"><span>学习使我快乐。</span>文章列表</h2>
      <div class="navtab">
        <!--<div class="search">-->
          <!--<form action="/e/search/index.php" method="post" name="searchform" id="searchform">-->
            <!--<input name="keyboard" id="keyboard" class="input_text" value="请输入关键字" style="color: rgb(153, 153, 153);" onfocus="if(value=='请输入关键字'){this.style.color='#000';value=''}" onblur="if(value==''){this.style.color='#999';value='请输入关键字'}" type="text">-->
            <!--<input name="show" value="title" type="hidden">-->
            <!--<input name="tempid" value="1" type="hidden">-->
            <!--<input name="tbname" value="news" type="hidden">-->
            <!--<input name="Submit" class="input_submit" value="搜索" type="submit">-->
          <!--</form>-->
        <!--</div>-->
        <!--<ul class="navlist" id="pageContent">-->
          <!--<li><a href="#">这里可以考虑放个啥东西？</a></li>-->
        <!--</ul>-->
        <script language="javascript">
            var obj=null;
            var As=document.getElementById('pageContent').getElementsByTagName('a');
            obj = As[0];
            for(i=1;i<As.length;i++){if(window.location.href.indexOf(As[i].href)>=0)
            obj=As[i];}
            obj.id='pagecurrent'
        </script>
      </div>
      <div class="newblogs">
        <h2 class="hometitle">全部文章(总共{{ arts | length }}篇)</h2>
        <ul>
            {% for article in articles %}
              <li>
                <h3 class="blogtitle">
                    <!--点击标签跳转-->
                  <!--<span><a href="#" title="" target=""-->
                           <!--class="classname">{{ article.art_tp.tp_name }}</a></span>-->
                    <!--点击标签不跳转-->
                  <span><font class="classname">{{ article.art_tp.tp_name }}</font></span>
                    <a href="{{ url_for('web.info', id=article.id) }}"
                       target="_blank" >{{ article.title }}</a>
                </h3>
                <div class="bloginfo"><span class="blogpic">
                    <a href="{{ url_for('web.info', id=article.id) }}" title="{{ article.title }}" target="_blank">
                        <img src="/static/web/images/b01.jpg" alt="" /></a></span>
                  <p>{{ article.desc }}</p>
                </div>
                <div class="autor"><span class="lm f_l"></span>
                    <span class="dtime f_l">{{ article.create_date }}</span>
                    <!--<span class="viewnum f_l">浏览（<a href="/">999</a>）</span>-->
                    <span class="f_r">
                        <a href="{{ url_for('web.info', id=article.id) }}" target="_blank" class="more">阅读原文>></a>
                    </span>
                </div>
                <div class="line"></div>
              </li>
            {% endfor %}
        </ul>
         <div class="pagelist">
             <a href="{{ url_for('web.art_list', id=id-1) }}">&nbsp;上一页</a>
             &nbsp;<a {% if id==1 %} style="background-color:#9999ff;" {% endif %}
                 href="{{ url_for('web.art_list', id=1) }}">1</a>
             &nbsp;<a {% if id==2 %} style="background-color:#9999ff;" {% endif %}
                 href="{{ url_for('web.art_list', id=2) }}">2</a>
             &nbsp;<a {% if id==3 %} style="background-color:#9999ff;" {% endif %}
                 href="{{ url_for('web.art_list', id=3) }}">3</a>
             &nbsp;<a href="{{ url_for('web.art_list', id=id+1) }}">下一页</a>
         </div>

      </div>
      <div class="rbox">

        <div class="paihang">
          <h2 class="hometitle">本栏推荐</h2>
          <ul>
              {% for article in arts %}
              {% if loop.index < 4 %}
                <li><b><a href="{{ url_for('web.info', id=article.id) }}" target="_blank">{{ article.title }}...</a></b>
                  <p><i><img src="/static/web/images/t02.jpg"  /></i>{{ article.desc }}...</p>
                </li>
              {% endif %}
              {% endfor %}
          </ul>
        </div>

        <div class="weixin">
          <h2 class="hometitle">个人微信</h2>
          <ul>
            <img src="/static/web/images/wx.jpg">
          </ul>
        </div>
      </div>

    </article>
{% endblock %}