zmblog/back/models.py
"""==========zhuming=========="""
from datetime import datetime

from flask_sqlalchemy import SQLAlchemy

db = SQLAlchemy()


class User(db.Model):
    id = db.Column(db.Integer, primary_key=True, autoincrement=True)  # 用户id
    username = db.Column(db.String(20), unique=True, nullable=False)  # 用户名
    password = db.Column(db.String(255), nullable=False)  # 密码
    email = db.Column(db.String(50), unique=True)  # 邮箱
    is_delete = db.Column(db.Boolean, default=0)  # 账号状态（1已删除，0正常）
    regisdate = db.Column(db.DateTime, default=datetime.now)  # 注册账号时间

    __tablename__ = 'user'

    def save(self):
        db.session.add(self)
        db.session.commit()

    def delete(self):
        db.session.delete(self)
        db.session.commit()


class Article_type(db.Model):
    id = db.Column(db.Integer, primary_key=True, autoincrement=True)  # 文章分类id
    tp_name = db.Column(db.String(20), unique=True, nullable=False)  #  文章分类名
    arts = db.relationship('Article', backref='art_tp')  # 关联文章

    __tablename__ = 'article_type'

    def save(self):
        db.session.add(self)
        db.session.commit()

    def delete(self):
        db.session.delete(self)
        db.session.commit()


class Article(db.Model):
    id = db.Column(db.Integer, primary_key=True, autoincrement=True)  # 文章id
    title = db.Column(db.String(20), unique=True, nullable=False)  # 文章标题
    desc = db.Column(db.String(100), nullable=False)  # 文章简介
    content = db.Column(db.Text, nullable=False)  # 文章内容
    create_date = db.Column(db.DateTime, default=datetime.now)  # 文章创建时间
    tp_id = db.Column(db.Integer, db.ForeignKey('article_type.id'))  # 外键关联文章分类id

    __tablename__ = 'article'

    def save(self):
        db.session.add(self)
        db.session.commit()

    def delete(self):
        db.session.delete(self)
        db.session.commit()

zmblog/back/__init__.py
"""==========zhuming=========="""


def main():
    pass


if __name__ == '__main__':
    main()

zmblog/back/views.py
from flask import Blueprint, render_template, request, redirect, url_for, session
from werkzeug.security import generate_password_hash, check_password_hash

from back.models import User, db, Article, Article_type
from utils.functions import is_login

# 创建管理后台的蓝图对象
back_blue = Blueprint('back', __name__)


@back_blue.route('/index/')
@is_login
def index():
    return render_template('/back/index.html')


@back_blue.route('/register/', methods=['GET', 'POST'])
def register():
    if request.method == 'GET':
        return render_template('/back/register.html')
    if request.method == 'POST':
        username = request.form.get('username')
        password = request.form.get('password')
        password2 = request.form.get('password2')
        if username and password and password2:
            user = User.query.filter(User.username == username).first()
            if user:
                error = '该用户名已被注册，请重新注册'
                return render_template('back/register.html', error=error)
            if password != password2:
                error = '请确认两次输入密码相同'
                return render_template('back/register.html', error=error)
            # 添加数据
            user = User()
            user.username = username
            user.password = generate_password_hash(password)
            user.save()
            return redirect(url_for('back.login'))
        else:
            error = '请输入完整信息'
            return render_template('back/register.html', error=error)


@back_blue.route('/login/', methods=['GET', 'POST'])
def login():
    if request.method == 'GET':
        return render_template('back/login.html')
    if request.method == 'POST':
        username = request.form.get('username')
        password = request.form.get('password')
        user = User.query.filter(User.username == username).first()
        if not user:
            error = '该用户没有注册，请前往注册'
            return render_template('back/login.html', error=error)
        if not check_password_hash(user.password, password):
            error = '密码错误，请重新输入'
            return render_template('back/login.html', error=error)
        # 用户名和密码都对，判断是否已被注销
        if user.is_delete == 1:
            error = '该账号已被注销，请另外注册'
            return render_template('back/login.html', error=error)
        # 用户名和密码都对，设置session
        session['user_id'] = user.id
        return redirect(url_for('back.index'))


# 安全退出
@back_blue.route('/logout/')
@is_login
def logout():
    del session['user_id']
    return redirect(url_for('back.login'))


# 用户列表
@back_blue.route('/user_list/', methods=['GET', 'POST'])
@is_login
def user_list():
    if request.method == 'GET':
        users = User.query.all()
        # 取出没有被删除的用户
        users = [user for user in users if user.is_delete == 0]
        return render_template('back/user_list.html', users=users)


# 删除用户
@back_blue.route('/del_user/<int:id>/', methods=['GET', 'POST'])
@is_login  # 装饰器里添加不定长参数！！！
def del_user(id):
    # 删除用户的同时应该删除对应的session,但是这里删除session,就当前浏览器的session都删了，就会返回登录界面，应该要有个超级管理员
    del session['user_id']
    user = User.query.get(id)
    print(user.is_delete)
    user.is_delete = 1
    user.save()
    print(user.is_delete)
    return redirect(url_for('back.user_list'))


# 文章分类
@back_blue.route('/article_category_list/', methods=['GET', 'POST'])
@is_login
def article_category_list():
    if request.method == 'GET':
        art_types = Article_type.query.all()
        return render_template('back/article_category_list.html', art_types=art_types)


# 添加文章分类
@back_blue.route('/add_article_category/', methods=['GET', 'POST'])
@is_login
def add_article_category():
    if request.method == 'GET':
        return render_template('back/add_article_category.html')
    if request.method == 'POST':
        category = request.form.get('category')
        if category:
            # 判断有没有和已有的分类名重复
            article_type = Article_type.query.filter(Article_type.tp_name == category).first()
            if article_type:
                error = '该分类名已存在，请重新输入'
                return render_template('back/add_article_category.html', error=error)
            # 保存分类信息
            art_type = Article_type()
            art_type.tp_name = category
            art_type.save()
            return redirect(url_for('back.article_category_list'))
        error = '请输入分类信息'
        return render_template('back/add_article_category.html', error=error)


# 删除文章分类
@back_blue.route('/del_art_category/<int:id>/', methods=['GET', 'POST'])
@is_login
def del_art_category(id):
    art_type = Article_type.query.get(id)
    art_type.delete()
    return redirect(url_for('back.article_category_list'))


# 修改文章分类
@back_blue.route('/update_category/<int:id>/', methods=['GET', 'POST'])
@is_login
def update_category(id):
    if request.method == 'GET':
        art_type = Article_type.query.get(id)
        return render_template('back/add_article_category.html', art_type=art_type)
    if request.method == 'POST':
        category = request.form.get('category')
        if category:
            # 判断有没有和已有的分类名重复
            article_type = Article_type.query.filter(Article_type.tp_name == category).first()
            if article_type:
                error = '该分类名已存在，请重新输入'
                return render_template('back/add_article_category.html', error=error)
            # 保存分类信息
            art_type = Article_type.query.get(id)
            art_type.tp_name = category
            art_type.save()
            return redirect(url_for('back.article_category_list'))
        error = '请输入分类信息'
        return render_template('back/add_article_category.html', error=error)


# 文章列表
@back_blue.route('/article_list/', methods=['GET', 'POST'])
@is_login
def article_list():
    if request.method == 'GET':
        articles = Article.query.order_by(-Article.id).all()
        return render_template('back/article_list.html', articles=articles)


# 添加文章
@back_blue.route('/add_article/', methods=['GET', 'POST'])
@is_login
def add_article():
    if request.method == 'GET':
        art_types = Article_type.query.all()
        return render_template('back/add_article.html', art_types=art_types)
    if request.method == 'POST':
        title = request.form.get('title')
        tp_id = request.form.get('type')
        desc = request.form.get('desc')
        content = request.form.get('content')
        if title and type and desc and content:
            # 判断标题有没有重复的
            article = Article.query.filter(Article.title == title).first()
            if article:
                error = '该标题已存在，请重新编辑'
                art_types = Article_type.query.all()
                return render_template('back/add_article.html', error=error, art_types=art_types)
            article = Article()
            article.title = title
            article.tp_id = tp_id
            article.desc = desc
            article.content = content
            article.save()
            return redirect(url_for('back.article_list'))
        error = '请填写完整信息'
        art_types = Article_type.query.all()
        return render_template('back/add_article.html', error=error, art_types=art_types)


# 删除文章
@back_blue.route('/del_article/<int:id>', methods=['GET', 'POST'])
@is_login
def del_article(id):
    article = Article.query.get(id)
    article.delete()
    return redirect(url_for('back.article_list'))


# 修改文章
@back_blue.route('/update_article/<int:id>', methods=['GET', 'POST'])
@is_login
def update_article(id):
    if request.method == 'GET':
        # 获取所有分类
        art_types = Article_type.query.all()
        # 获取文章对象
        article = Article.query.get(id)
        return render_template('back/add_article.html', art_types=art_types, article=article)
    if request.method == 'POST':
        title = request.form.get('title')
        tp_id = request.form.get('type')
        desc = request.form.get('desc')
        content = request.form.get('content')
        if title and type and desc and content:
            # 判断标题有没有和别的标题重复的，这里不包括被修改的文章本身
            article = Article.query.filter(Article.title == title).first()
            original_title = Article.query.get(id).title
            if article and article.title != original_title:
                error = '该标题已存在，请重新编辑'
                art_types = Article_type.query.all()
                article = Article.query.get(id)
                return render_template('back/add_article.html', error=error, art_types=art_types, article=article)
            article = Article.query.get(id)
            article.title = title
            article.tp_id = tp_id
            article.desc = desc
            article.content = content
            article.save()
            return redirect(url_for('back.article_list'))
        error = '请填写完整信息'
        art_types = Article_type.query.all()
        return render_template('back/add_article.html', error=error, art_types=art_types)


# 测试tinymce
@back_blue.route('/', methods=['GET', 'POST'])
def editor():
    #如果是post方法就返回tinymce生成html代码，否则渲染editor.html
    if request.method=='POST':
        return request.form['content']
    return render_template('back/editor.html')

zmblog/web/views.py
"""==========zhuming=========="""

from flask import Blueprint, render_template, redirect, url_for, request

# 创建管理前端的蓝图对象
from back.models import Article

web_blue = Blueprint('web', __name__)


# 首页
@web_blue.route('/', methods=['GET', 'POST'])
def index():
    if request.method == 'GET':
        # 倒序排列文章，最新文章就放5个
        articles = Article.query.order_by(-Article.id).all()
        return render_template('web/index.html', articles=articles)


# 阅读全文/展示全文的页面
@web_blue.route('/info/<int:id>/', methods=['GET', 'POST'])
def info(id):
    if request.method == 'GET':
        article = Article.query.get(id)
        articles = Article.query.order_by(-Article.id).all()
        # 在数据库中id的自动生成有可能被人为的打断顺序，所以不能直接通过对于id的加减进行查询
        # 只能通过取出所有id保存在列表中，根据下标的加减来查询
        ids = [art.id for art in articles]
        # 判断是否只有一篇文章
        pre_article = ''
        if len(ids) > 1:
            pre_id = ids[ids.index(id) - 1]
            pre_article = Article.query.get(pre_id)
        # 判断是否为最后一篇
        next_article = ''
        if id != min(ids):
            next_id = ids[ids.index(id) + 1]
            next_article = Article.query.get(next_id)
        return render_template('web/info.html', article=article,
                               ids=ids, pre_article=pre_article, next_article=next_article)


# 文章列表
@web_blue.route('/list/<int:id>', methods=['GET', 'POST'])
def art_list(id):
    if request.method == 'GET':
        arts = Article.query.order_by(-Article.id).all()
        if id < 1:
            id = 1
        if id*4 > len(arts):
            id = len(arts)//4 + 1
        page = id
        articles = Article.query.order_by(-Article.id).offset((page-1)*4).limit(4).all()
        return render_template('web/list.html', articles=articles, id=id, arts=arts)


# 关于我
@web_blue.route('/about/', methods=['GET', 'POST'])
def about():

    return render_template('web/about.html')


# 留言
@web_blue.route('/gbook/', methods=['GET', 'POST'])
def gbook():

        return render_template('web/gbook.html')

zmblog/templates/back/add_article.html
{% extends 'back/base_main.html' %}

{% block title %}
    添加文章
{% endblock%}

{% block css %}
    <!--为了富文本编辑器，放弃滚动条-->
    <link rel="stylesheet" type="text/css" href="/static/back/css/style_no_scroll.css">
{% endblock %}

{% block js %}
    <script src="/static/back/js/jquery.js"></script>
    <!--<script src="/static/back/js/jquery.mCustomScrollbar.concat.min.js"></script>-->

    {#    使用jinjia导入两个js#}
     <!--没有滚动条就可以使用tinymce了，应该是插件相互冲突的原因-->
    <script src="{{ url_for('static', filename='tinymce/js/tinymce/tinymce.min.js') }}"></script>
    <script src="{{ url_for('static', filename='tinymce/tinymce_setup.js') }}"></script>
    <!--<script type="text/javascript" src="/static/kindeditor/kindeditor-all.js"></script>-->
    <!--<script type="text/javascript" src="/static/kindeditor/lang/zh-CN.js"></script>-->
    <!--<script type="text/javascript">-->
        <!--KindEditor.ready(function(K) {-->
                <!--window.editor = K.create('#editor_id');-->
        <!--});-->
   <!--</script>-->

{% endblock %}

{% block content %}

    <section class="rt_wrap mCustomScrollbar">

        <div class="rt_content">
            <div class="page_title">
                <h2 class="fl">文章详情</h2>
                <a class="fr top_rt_btn" href="{{ url_for('back.article_list') }}">返回文章列表</a>
            </div>
            <form action="" method="post">
                <input type='hidden' name='csrfmiddlewaretoken' value='q3tTrBuDcMhfvSS9x2u0yQAyRbboSQuyMyt42kgwgKS0rKxCv31hIWTsS3ULhZn7' />
                <section>
                    <ul class="ulColumn2">
                        <font style="font-weight:900;margin-left:200px;color:red;">{{ error }}</font>
                        <li>
                            <span class="item_name" style="width:120px;">标题：</span>
                            <input type="text" name="title" class="textbox textbox_295"
                                   maxlength="20" placeholder="不超过20个字"
                                   {% if article %} value="{{ article.title }}" {% else %}
                                   placeholder="文章标题..." {% endif %}/>
                        </li>
                        <li>
                            <span class="item_name" style="width:120px;">文章类型：</span>
                            <select class="select" name="type" style="width:307px;">
                                {% for art_type in art_types %}
                                {% if article %}
                                    <option value="{{ art_type.id }}"
                                        {% if article.tp_id == art_type.id %} selected="selected" {% endif %}>{{ art_type.tp_name }}</option>
                                {% else %}
                                    <option value="{{ art_type.id }}">{{ art_type.tp_name }}</option>
                                {% endif %}
                                {% endfor %}
                            </select>

                        </li>
                        <li>
                            <span class="item_name" style="width:120px;">文章描述：</span>
                            {% if article %}
                            <!--<input type="text" name="desc" maxlength="100"  class="textbox textbox_295" placeholder="文章简介不超过100个字..."/>-->
                            <textarea name="desc" maxlength="100"
                                      class="textbox textbox_295">{{ article.desc }}</textarea>
                            {% else %}
                            <textarea name="desc" maxlength="100"  class="textbox textbox_295"
                                      placeholder="文章简介不超过100个字..."></textarea>
                            {% endif %}
                        </li>

                        <li>
                            <span class="item_name" style="width:120px;">文章内容：</span>
                            <label style="display:inline-block;padding:15px;width:800px;
                                    background:#f8f8f8;vertical-align:text-top;">
                                <textarea id="editor_id" name="content" style="width:800px;height:300px;">
                                    {% if article %}
                                    {{ article.content }}
                                    {% else %}
                                    &lt;strong&gt;HTML内容&lt;/strong&gt;
                                    {% endif %}
                                </textarea>
                            </label>
                        </li>

                        <li>
                            <span class="item_name" style="width:120px;"></span>
                            <input type="submit" class="link_btn"/>
                        </li>
                    </ul>
                </section>
            </form>
        </div>
    </section>






{% endblock %}

zmblog/templates/back/add_article_category.html
{% extends 'back/base_main.html' %}

{% block title %}
    添加文章分类
{% endblock %}

{% block content %}

    <section class="rt_wrap mCustomScrollbar">

        <div class="rt_content">
            <div class="page_title">
                <h2 class="fl">添加文章分类</h2>
                <a class="fr top_rt_btn" href="{{ url_for('back.article_category_list') }}">返回文章分类列表</a>
            </div>
            <form action="" method="post">
                <input type='hidden' name='csrfmiddlewaretoken' value='etyOfxyfqllVlf0tMSkvPkrzgjEdjgNSAYyZQgk8ujWGh7FWKTRMZqKthbnAIpGr' />
                <section>
                    <ul class="ulColumn2">
                        <li style="font-weight:900;margin-left:20px;">
                            {{ error }}
                        </li>
                        <li>
                            <span class="item_name" style="width:120px;">文章分类名称：</span>
                            {% if art_type %}
                            <input type="text" name="category" value="{{ art_type.tp_name }}"
                                   maxlength="20" placeholder="不超过20个字" style="width:200px;">
                            {% else %}
                            <input type="text" name="category" value=""
                                   maxlength="20" placeholder="不超过20个字" style="width:200px;">
                            {% endif %}
                        </li>

                        <li>
                            <span class="item_name" style="width:120px;"></span>
                            <input type="submit" class="link_btn"/>
                        </li>
                    </ul>
                </section>
            </form>
        </div>
    </section>


{% endblock %}

zmblog/templates/back/article_category_list.html
{% extends 'back/base_main.html' %}

{% block title %}
    文章分类列表
{% endblock %}

{% block content %}

    <section class="rt_wrap content mCustomScrollbar">
        <div class="rt_content">
            <div class="page_title">
                <h2 class="fl">文章分类列表</h2>
                <a href="{{ url_for('back.add_article_category') }}" class="fr top_rt_btn add_icon">添加文章分类</a>
            </div>
            <table class="table">
                <tr>
                    <th>文章类型名</th>
                    <th>操作</th>
                </tr>
                {% for art_type in art_types %}
                    <tr>
                        <td class="center">
                            {{ art_type.tp_name }}
                        </td>
                        <td class="center">
                            <a href="{{ url_for('back.update_category', id=art_type.id) }}"
                               title="编辑" class="link_icon">&#101;</a>
                            <a href="{{ url_for('back.del_art_category', id=art_type.id) }}"
                               title="删除" class="link_icon">&#100;</a>
                        </td>
                    </tr>
                {% endfor %}
            </table>
        </div>
    </section>

{% endblock %}

zmblog/templates/back/article_list.html
{% extends 'back/base_main.html' %}

{% block title %}
    文章列表页面
{% endblock%}

{% block content %}

    <section class="rt_wrap content mCustomScrollbar">
        <div class="rt_content">
            <div class="page_title">
                <h2 class="fl">文章列表</h2>
                <a href="{{ url_for('back.add_article') }}" class="fr top_rt_btn add_icon">添加文章</a>
            </div>
            <table class="table">
                <tr>
                    <th>标题</th>
                    <th>文章类型</th>
                    <th>文章描述</th>
                    <th>创建时间</th>
                    <th>操作</th>
                </tr>
                {% for article in articles %}
                    <tr>
                        <td class="center">{{ article.title }}</td>
                        <td class="center">{{ article.art_tp.tp_name }}</td>
                        <td class="center">{{ article.desc }}</td>
                        <td class="center">{{ article.create_date }}</td>

                        <td class="center">
                            <a href="{{ url_for('back.update_article', id=article.id) }}" title="编辑" class="link_icon">&#101;</a>
                            <a href="{{ url_for('back.del_article', id=article.id) }}"
                               title="删除" class="link_icon">&#100;</a>
                        </td>
                    </tr>
                {% endfor %}
            </table>
            <aside class="paging">
                <!--这里通过传一个页数id来确定链接，这个功能启用之后不用忘了在业务逻辑中添加一个参数id-->
                <!--<a>当前{{ id }}页</a>-->
                <!--<a href="{{ url_for('back.article_list', id=1) }}">第一页</a>-->

                    <!--<a href="{{ url_for('back.article_list', id=1) }}"> 1 </a>-->

                    <!--<a href="{{ url_for('back.article_list', id=2) }}"> 2 </a>-->

                    <!--<a href="{{ url_for('back.article_list', id=3) }}"> 3 </a>-->

                <!--<a href="">最后一页</a>-->
            </aside>
        </div>
    </section>

{% endblock %}

zmblog/templates/back/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">

    <title>
        {% block title %}
        {% endblock %}
    </title>

    {% block css %}
    {% endblock %}

    {% block js %}
    {% endblock %}

</head>
<body>
    {% block header %}
    {% endblock %}

    {% block aside %}
    {% endblock %}

    {% block content %}
    {% endblock %}

</body>
</html>

zmblog/templates/back/base_main.html
{% extends '/back/base.html' %}

{% block css %}
    <link rel="stylesheet" type="text/css" href="/static/back/css/style.css">
{% endblock %}

{% block js %}
    <script src="/static/back/js/jquery.js"></script>
    <script src="/static/back/js/jquery.mCustomScrollbar.concat.min.js"></script>
{% endblock %}

{% block header %}
    <header>
        <h1><a href="{{ url_for('back.index') }}"><img src="/static/back/images/admin_logo.png"/></a></h1>
        <ul class="rt_nav">
            <li><a href="{{ url_for('web.index') }}" target="_blank" class="website_icon">站点首页</a></li>
            <li><a href="{{ url_for('back.user_list') }}" class="set_icon">账号设置</a></li>
            <li><a href="{{ url_for('back.logout') }}" class="quit_icon">安全退出</a></li>
        </ul>
    </header>
{% endblock %}

{% block aside %}
    <aside class="lt_aside_nav content mCustomScrollbar">
        <h2><a href="">博客后台菜单栏</a></h2>
        <ul>
            <li>
                <dl>
                    <dt>文章管理</dt>
                    <!--当前链接则添加class:active-->
                    <dd><a href="{{ url_for('back.article_category_list') }}">文章分类</a></dd>
                    <dd><a href="{{ url_for('back.article_list') }}">文章列表</a></dd>
                </dl>
            </li>

            <li>
                    <dl>
                        <dt>用户管理</dt>
                        <dd><a href="{{ url_for('back.user_list') }}">用户列表</a></dd>
                    </dl>
                </li>
        </ul>
    </aside>
{% endblock %}

zmblog/templates/back/editor.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>富文本编辑器测试</title>
{#    使用jinjia导入两个js#}
    <script src="{{ url_for('static', filename='tinymce/js/tinymce/tinymce.min.js') }}"></script>
    <script src="{{ url_for('static', filename='tinymce/tinymce_setup.js') }}"></script>
</head>
<body>
     <form  method="post" action="">
                            <span class="item_name" style="width:120px;">文章内容：</span>
                            <label style="display:inline-block;padding:15px;width:800px;background:#f8f8f8;vertical-align:text-top;">-->
                                <textarea id="editor_id" name="content" style="width:800px;height:300px;">
                                    {% if article %}
                                    {{ article.content }}
                                    {% else %}
                                    &lt;strong&gt;HTML内容&lt;/strong&gt;
                                    {% endif %}
                                </textarea>
                            </label>
    </form>
</body>
</html>

zmblog/templates/back/index.html
{% extends '/back/base_main.html' %}

{% block title %}
    后台管理系统首页
{% endblock %}


{% block js %}
    {{ super() }}
    <script>
        (function($){
            $(window).load(function(){

                $("a[rel='load-content']").click(function(e){
                    e.preventDefault();
                    var url=$(this).attr("href");
                    $.get(url,function(data){
                        $(".content .mCSB_container").append(data); //load new content inside .mCSB_container
                        //scroll-to appended content
                        $(".content").mCustomScrollbar("scrollTo","h2:last");
                    });
                });

                $(".content").delegate("a[href='top']","click",function(e){
                    e.preventDefault();
                    $(".content").mCustomScrollbar("scrollTo",$(this).attr("href"));
                });

            });
        })(jQuery);
    </script>
{% endblock %}

{% block content %}
    <section class="rt_wrap content mCustomScrollbar">
        <div class="rt_content">
            <h1 style="color:red;font-size:20px;font-weight:bold;text-align:center;">
                博客管理后台
            </h1>
            <br>
            <p>博客管理采用Flask开发，存储数据库为关系型数据库Mysql</p>
            <br>
            <p>博客后台集中功能为：文章管理、文章分类、文章列表、用户管理、用户列表等模块</p>


        </div>
    </section>
{% endblock%}

zmblog/templates/back/login.html
{% extends '/back/base.html' %}

{% block title %}
    用户登录
{% endblock %}

{% block css %}
    <link rel="stylesheet" type="text/css" href="/static/back/css/style.css" />
    <style>
    body{height:100%;background:#16a085;overflow:hidden;}
    canvas{z-index:-1;position:absolute;}
    </style>
{% endblock %}

{% block js %}
    <script src="/static/back/js/jquery.js"></script>
    <script src="/static/back/js/verificationNumbers.js"></script>
    <script src="/static/back/js/Particleground.js"></script>
    <script src="/static/back/js/verificationNumbers.js"></script>
    <script>
        $(document).ready(function() {
          //粒子背景特效
          $('body').particleground({
            dotColor: '#5cbdaa',
            lineColor: '#5cbdaa'
          });
          //验证码
          createCode();
          //测试提交，对接程序删除即可
          $(".submit_btn").click(function(){
              location.href="index.html";
              });
        });
    </script>
{% endblock %}

{% block content %}
<form action="" method="post">
    <dl class="admin_login">
        <dt>
            <strong>站点后台管理系统</strong>
            <em>Management System</em>
            <strong style="color:black;font-size:20px;">{{ error }}</strong>
        </dt>
        <dd class="user_icon">
            <input type="text" placeholder="账号" name="username" class="login_txtbx"/>
        </dd>
        <dd class="pwd_icon">
            <input type="password" placeholder="密码" name="password" class="login_txtbx"/>
        </dd>
        <dd>
            <input type="submit" value="立即登录" class="submit_btn"/>
        </dd>
        <dd>
        <button class="submit_btn" ><a href="{{ url_for('back.register') }}">注册</a></button>
        <p>© 2015-2016 DeathGhost 版权所有</p>
        <!--<p>陕B2-20080224-1</p>-->
        </dd>
    </dl>
</form>
{% endblock %}

zmblog/templates/back/user_list.html
{% extends 'back/base_main.html' %}

{% block title %}
    用户管理界面
{% endblock %}

{% block content %}
<section class="rt_wrap content mCustomScrollbar">
 <div class="rt_content">
    <div class="page_title">
        <h2 class="fl">用户列表</h2>
        <!--<a href="user_detail.html" class="fr top_rt_btn add_icon">添加新会员</a>-->
    </div>
    <table class="table">
        <tr>
            <th>Id</th>
            <th>用户名</th>
            <th>电子邮件</th>
            <th>注册时间</th>
            <th>操作</th>
        </tr>
        {% for user in users %}
            <tr>
                <td class="center">{{ user.id }}</td>
                <td class="center">{{ user.username }}</td>
                <td class="center">{{ user.email }}</td>
                <td class="center">{{ user.regisdate }}</td>

                <td class="center">
                    <!--<a href="user_detail.html" title="编辑" class="link_icon">&#101;</a>-->
                    <a href="{{ url_for('back.del_user', id=user.id) }}"
                       title="删除" class="link_icon">&#100;</a>
                </td>
            </tr>
        {% endfor %}
        </table>
        <aside class="paging">
            <!--<a>第一页</a>-->
            <!--<a>1</a>-->
            <!--<a>2</a>-->
            <!--<a>…</a>-->
            <!--<a>4</a>-->
            <!--<a>最后一页</a>-->
        </aside>
 </div>
</section>

{% endblock %}